spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: 'kafka.pks.kirklab.io'
            bindings:
                logEvents:
                    destination: todos-logs
                errorEvents:
                    destination: todos-errors
                containerMetricEvents:
                    destination: todos-container-metrics
cf:
    api: api.run.pas.kirklab.io
    username: bkirkland
    password: howdy
    organization: retro
    space: todo
    domain: apps.pas.kirklab.io
    skipSslValidation: true
