spring:
    cloud:
        stream:
            kafka:
                binder:
                    configuration:
                        sasl:
                            mechanism: PLAIN
                            jaas:
                                config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username=test password=test123;'
                        security:
                            protocol: SASL_PLAINTEXT
                    brokers: 'kafka.pks.kirklab.io'
            bindings:
                logEvents:
                    destination: todos-logs
                errorEvents:
                    destination: todos-errors
                containerMetricEvents:
                    destination: todos-container-metrics
cf:
    api: api.run.pas.kirklab.io
    username: bkirkland
    password: user123
    organization: bkirkland
    space: todo
    domain: apps.pas.kirklab.io
    skipSslValidation: true
